name: Create cherry-pick PR
on:
  pull_request_target:
    branches:
      - 'next'
      - 'v*.x'
      - 'master'
    types: ['closed']

permissions: {}

jobs:
  create_pr:
    name: Create cherry-pick PR
    uses: mui/mui-public/.github/workflows/prs_create-cherry-pick-pr.yml@428843a303d23c4c904fc740058e33e1a8b95c85 # master
    permissions:
      contents: write
      pull-requests: write
